name: movie_sctreaming
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  go_router: ^14.2.6
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.3.2
  youtube_player_flutter: ^9.0.3
  flutter_inappwebview: ^6.0.0
  video_player: ^2.9.1
  uuid: ^4.5.0
  firebase_messaging: ^14.7.10
  awesome_notifications: ^0.9.3+1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  generate: true
  uses-material-design: true

